# ~/.config/sway/conf.d/input.conf

input type:keyboard {
    xkb_layout "latam,us"
    xkb_variant ",altgr-intl"
    xkb_options "grp:alt_shift_toggle" 
    repeat_delay 300
    repeat_rate 50
}

input type:touchpad {
    tap enabled
    natural_scroll enabled
    scroll_method two_finger
    click_method clickfinger
    pointer_accel 0.3
    dwt enabled
    middle_emulation enabled
}

input type:mouse {
    accel_profile flat
    pointer_accel 0
}

# Configuración para el mando - Usando IDs numéricos para evitar errores de sintaxis
input "6473:1026:GamePadPlus_V3" events disabled
input "6473:1026:GamePadPlus_V3_Mouse" events disabled
input "6473:1026:GamePadPlus_V3_Consumer_Control" events disabled

# Desactivar el teclado falso del mouse Sinowealth para evitar que escriba
input "9610:4103:SINOWEALTH_Game_Mouse_Keyboard" {
    events disabled
}