# ~/.config/sway/conf.d/windows.conf
# Comportamiento tipo Hyprland

# Diálogos reales
for_window [window_type="dialog"] floating enable
for_window [window_role="dialog"] floating enable
for_window [window_role="task_dialog"] floating enable

# Apps específicas
for_window [app_id="pavucontrol"] floating enable
for_window [app_id="blueman-manager"] floating enable
for_window [app_id="nm-connection-editor"] floating enable
for_window [app_id="thunar" title="File Operation Progress"] floating enable

# Picture in Picture
for_window [title="Picture-in-Picture"] floating enable, sticky enable
for_window [title="Picture-in-Picture"] inhibit_idle visible

# Chromium fullscreen inhibe idle (correcto)
for_window [app_id="chromium"] inhibit_idle fullscreen


# Opacidad de Ventanas
# Aplica a todas las ventanas que tengan un app_id (nativo Wayland)
for_window [app_id=".*"] opacity 0.96

# Aplica a las ventanas flotantes (como indicas en tu línea 26)
for_window [floating] opacity 0.96

# Para aplicaciones de X11 (vía XWayland), usa 'class' en lugar de 'app_id'
for_window [class=".*"] opacity 0.96
