# ~/.config/sway/conf.d/autostart.conf

# Noctalia Shell
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway QT_QPA_PLATFORMTHEME QT_QPA_PLATFORM
exec systemctl --user stop xdg-desktop-portal-wlr
exec systemctl --user stop xdg-desktop-portal
exec qs -c noctalia-shell
